version: '3.3'
services:
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: